version: '3'

services:
  nginx:
    restart: always
    image: shayim/multi-nginx
    ports:
      - 80:80

  client:
    image: shayim/multi-client

  api:
    image: shayim/multi-server

  worker:
    image: shayim/multi-worker
